# Generated by Django 2.0.2 on 2018-03-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perguntas',
            fields=[
                ('id_pergunta', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id_quest', models.AutoField(primary_key=True, serialize=False)),
                ('data_entrada', models.DateField(auto_now=True)),
                ('data_final', models.DateField()),
                ('titulo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id_resposta', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id_resposta', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
